# ============================================================================
# STRAT Trading System - Horizontal Pod Autoscaler
# ============================================================================
# Auto-scaling configuration based on CPU, memory, and custom metrics
# ============================================================================

# ============================================================================
# STRAT Application HPA
# ============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: strat-app-hpa
  namespace: strat-trading
  labels:
    app: strat-trading
    component: app-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strat-app
  minReplicas: 2
  maxReplicas: 8
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metrics (if using custom metrics API)
  - type: Pods
    pods:
      metric:
        name: backtest_queue_length
      target:
        type: AverageValue
        averageValue: "10"
  - type: Pods
    pods:
      metric:
        name: active_trading_sessions
      target:
        type: AverageValue
        averageValue: "5"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# ============================================================================
# STRAT Dashboard HPA
# ============================================================================
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: strat-dashboard-hpa
  namespace: strat-trading
  labels:
    app: strat-trading
    component: dashboard-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strat-dashboard
  minReplicas: 1
  maxReplicas: 4
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85
  # Custom metrics for dashboard usage
  - type: Pods
    pods:
      metric:
        name: active_dashboard_users
      target:
        type: AverageValue
        averageValue: "20"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # 10 minutes - dashboard scaling is less urgent
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Max

---
# ============================================================================
# Vertical Pod Autoscaler (VPA) - Optional
# ============================================================================
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: strat-app-vpa
  namespace: strat-trading
  labels:
    app: strat-trading
    component: app-vpa
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: strat-app
  updatePolicy:
    updateMode: "Auto"  # Options: Off, Initial, Auto
  resourcePolicy:
    containerPolicies:
    - containerName: strat-app
      maxAllowed:
        cpu: 8000m
        memory: 16Gi
      minAllowed:
        cpu: 500m
        memory: 1Gi
      controlledResources: ["cpu", "memory"]
      controlledValues: RequestsAndLimits

---
# ============================================================================
# Pod Disruption Budget
# ============================================================================
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: strat-app-pdb
  namespace: strat-trading
  labels:
    app: strat-trading
    component: app-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: strat-trading
      component: app

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: strat-dashboard-pdb
  namespace: strat-trading
  labels:
    app: strat-trading
    component: dashboard-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: strat-trading
      component: dashboard