# ============================================================================
# STRAT Trading System - Kubernetes Namespace
# ============================================================================
# Dedicated namespace for STRAT trading system with resource quotas and limits
# ============================================================================

apiVersion: v1
kind: Namespace
metadata:
  name: strat-trading
  labels:
    app: strat-trading
    environment: production
    version: v1.0.0
    managed-by: kubernetes
  annotations:
    description: "STRAT Trading System - Production Environment"
    contact: "devops@strat-trading.com"

---
# ============================================================================
# Resource Quotas
# ============================================================================
apiVersion: v1
kind: ResourceQuota
metadata:
  name: strat-trading-quota
  namespace: strat-trading
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
    pods: "20"

---
# ============================================================================
# Limit Ranges
# ============================================================================
apiVersion: v1
kind: LimitRange
metadata:
  name: strat-trading-limits
  namespace: strat-trading
spec:
  limits:
  - default:
      cpu: "2000m"
      memory: "4Gi"
    defaultRequest:
      cpu: "500m"
      memory: "1Gi"
    type: Container
  - max:
      cpu: "8000m"
      memory: "16Gi"
    min:
      cpu: "100m"
      memory: "128Mi"
    type: Container